services:
  kafka:
    container_name: kafka
    image: apache/kafka:3.7.1
    ports:
      - 9092:9092
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # zookeeper:
  #   container_name: zookeeper
  #   image: zookeeper:3.7.0
  #   ports:
  #     - 2181:2181
